Add an ability to create regression tests for third party broker statements

diff --git a/regression_tests/test-tax-statement b/regression_tests/test-tax-statement
--- a/regression_tests/test-tax-statement
+++ b/regression_tests/test-tax-statement
@@ -3,11 +3,17 @@
 # Tax statement generation regression test
 #
 
-set -eu
+set -eux
 
-broker="$1"
-year="$2"
-statement_path="$3"
+if [ $# -ne 4 ]; then
+    echo "Invalid usage:" "$@"
+    exit 1
+fi
+
+config="$1"
+broker="$2"
+year="$3"
+statement_path="$4"
 
 reference_year=2019
 ((reference_short_year = reference_year - 2010))
@@ -16,4 +22,4 @@ cp "src/tax_statement/statement/testdata/filled.dc$reference_short_year" "$state
 [ "$year" -eq "$reference_year" ] ||
     sed -i "s/^\(DLSG            Decl\)$reference_year/\\1$year/" "$statement_path"
 
-./regression_tests/investments tax-statement "$broker" "$year" "$statement_path"
+./regression_tests/investments "$config" tax-statement "$broker" "$year" "$statement_path"
